{% set name = "pytest-testinfra" %}
{% set version = "10.1.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pytest-testinfra-{{ version }}.tar.gz
  sha256: a876f1453a01b58d94d9d936dd50344c2c01ac7880a2b41d15bdf233aed9cf1f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools_scm
  run:
    - pytest !=3.0.2
    - python >=3.6

test:
  imports:
    - testinfra
    - testinfra.backend
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pytest-dev/pytest-testinfra
  summary: Test infrastructures
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tschoonj
